version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file backend_pipeline.yaml --s3-bucket backend-pipeline --output-template-file output_backend_pipeline.yml
artifacts:
  type: zip
  files:
    - backend_pipeline.yaml
    - output_backend_pipeline.yml